### ISSUE TITLE
Converting ArchieML to Apple News Format

### ISSUE THREAD

**Issue by MatthewWeberTR** [reuters-graphics/bluprint_graphics-rig#47]
We should invest in a script to convert the JSON of text returned by runner get-google in conjunction with the metadata.json file to create an apple news format of articles.

this would require, to some degree, standardizing as many of the keys used in Archie as possible.  

I would imagine there would be room for bespoke keys that could be ignored, but things like text, photo, headline, dek, et cetera should be pulled and formatted by default. 

A default set of styles should be written and attached. 

This could vastly expidite the process of building apple news versions of stories. 

Attaching an example of the assets delivered for capitol mob piece. 
[reuters-crisis-at-the-capitol-anf.zip](https://github.com/reuters-graphics/bluprint_graphics-rig/files/5788212/reuters-crisis-at-the-capitol-anf.zip)

**Comment by hobbes7878** [comment]
Moving this effort over to Sveltekit rig
