### ISSUE TITLE
Fix ai2html check

### ISSUE THREAD

**Issue by hobbes7878** [reuters-graphics/bluprint_graphics-rig#50]
We should fix this up so folks are automatically getting our latest ai2html script:

https://github.com/reuters-graphics/bluprint_graphics-rig/blob/master/bin/checkAi2html/index.js

Two things, though:

1) Since it appears people are running more than one version of Illustrator, I think we need to walk/glob the applications directory and find ALL versions they have installed. So the SCRIPT in constants [here](https://github.com/reuters-graphics/bluprint_graphics-rig/blob/master/bin/checkAi2html/constants.js#L11) should really be an array of locations and we'll install to all of them.

2) Since we'll have to enter a password each time we want to write to that directory on our managed machines, we should _read_ the contents of the file if it already exists, and if it's the same as the latest, just skip it.

Assigning this to you @manas271196 'cause you are the involuntary king of ai2html :) but I'm around to help work out the details of the above.

**Comment by manas271196** [comment]
will take a look at this today
