### ISSUE TITLE
Accessibility checks for images and graphics

### ISSUE THREAD

**Issue by hobbes7878** [reuters-graphics/bluprint_graphics-rig#53]
Images should always have `alt` attributes Decorative images like section breakers or logos should have empty `alt` attributes.

Graphics sections should always have an `aria-describedby` attribute linked to another element on the page with text and that ID.

Preferably check these before build and prompt for missing.

More research TK: @AditiBhandariTR

**Comment by AditiBhandariTR** [comment]
using `aria-describedby` and `title` to label SVGs: https://fossheim.io/writing/posts/apple-dataviz-a11y-tutorial/

**Comment by hobbes7878** [comment]
Handling via Svelte preprocess checks in new Sveltekit rig going forward.
